import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"import { ThemeProvider as NextThemesProvider } from "next-themes"

const lora = Lora({
  subsets:["latin"],
  weight:["400","500"],
  style:["normal","italic"],
  variable:"--font-serif",
});

const dmSans = DM_Sans({
  subsets:["latin"],
  weight:["300","400","500","600"],
  variable:"--font-sans",
});

export const metadata = {
  title: "ai-mock-interview",
  description: "Generated by create next app",
};

export default function RootLayout({children}){
  return(
    <html lang="en" suppressHydrationWarning>
      <body className={`${lora.variable}${dmSans.variable} font-sans`}>
        <ThemeProvider
        attribute="class"
defaultTheme="system"
enableSystem
disabletTransitonOnChange>

        {/*header*/}
<main className="min-h-screen">   {children} </main>
{/*footer*/}
  </ThemeProvider>
        </body>
        </html>
  )
}
